promise.then(f1).catch(f2);
// если promise не выполнится, то в catch вернёт значение f2

promise.then(f1, f2);
// если promise не выполнится, то сразу вызовет f2 с ошибкой
